package com.ptmuk.power;

import java.util.LinkedHashMap;
import java.util.Map;

/** Generated by tools/pylons.py: number of block cells in each tower. Do not edit. */
public final class PylonCells {
    public static final Map<String, Integer> COUNTS = new LinkedHashMap<>();

    static {
        COUNTS.put("pylon_400kv", 740);
        COUNTS.put("pylon_400kv_tension", 730);
        COUNTS.put("pylon_400kv_terminal", 958);
        COUNTS.put("pylon_132kv", 368);
        COUNTS.put("t_pylon", 162);
        COUNTS.put("wood_pole_11kv", 14);
        COUNTS.put("h_pole_33kv", 26);
        COUNTS.put("pylon_275kv", 472);
        COUNTS.put("pylon_400kv_square", 758);
        COUNTS.put("pylon_400kv_angle", 698);
        COUNTS.put("bt_telephone_pole", 9);
    }

    private PylonCells() {
    }
}
