package com.ptmuk.power;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.ptmuk.PtmUk;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.phys.Vec3;

/**
 * Tower layout generated by tools/pylons.py: which block cells the tower occupies and where its
 * conductors attach, in the tower's own frame (line along z, arms along x, origin at the base
 * centre). Bundled in the jar, so client and server read the same file.
 */
public final class PylonData {
    public record Attach(Vec3 pos, int bundle, boolean earth) {
    }

    private static final Map<String, PylonData> CACHE = new ConcurrentHashMap<>();

    public final List<BlockPos> cells = new ArrayList<>();
    public final List<Attach> attach = new ArrayList<>();
    /** Per cell: steelwork bounds in block pixels (x0, y0, z0, x1, y1, z1), facing north. */
    public final List<double[]> boxes = new ArrayList<>();

    public static PylonData get(String name) {
        return CACHE.computeIfAbsent(name, PylonData::load);
    }

    private static PylonData load(String name) {
        PylonData data = new PylonData();
        String path = "/data/" + PtmUk.MOD_ID + "/pylons/" + name + ".json";
        try (InputStream in = PylonData.class.getResourceAsStream(path)) {
            if (in == null) {
                PtmUk.LOGGER.error("Missing pylon layout {}", path);
                return data;
            }
            JsonObject json = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            for (JsonElement e : json.getAsJsonArray("cells")) {
                JsonArray a = e.getAsJsonArray();
                data.cells.add(new BlockPos(a.get(0).getAsInt(), a.get(1).getAsInt(), a.get(2).getAsInt()));
            }
            if (json.has("boxes")) {
                for (JsonElement e : json.getAsJsonArray("boxes")) {
                    JsonArray a = e.getAsJsonArray();
                    double[] b = new double[6];
                    for (int i = 0; i < 6; i++) {
                        b[i] = a.get(i).getAsDouble();
                    }
                    data.boxes.add(b);
                }
            }
            for (JsonElement e : json.getAsJsonArray("attach")) {
                JsonArray a = e.getAsJsonArray();
                data.attach.add(new Attach(new Vec3(a.get(0).getAsDouble(), a.get(1).getAsDouble(), a.get(2).getAsDouble()),
                        a.get(3).getAsInt(), "earth".equals(a.get(4).getAsString())));
            }
        } catch (Exception ex) {
            PtmUk.LOGGER.error("Could not read pylon layout {}", path, ex);
        }
        return data;
    }

    /** Turns a tower-frame block offset to face the given way (north = as modelled). */
    public static BlockPos rotate(BlockPos p, Direction facing) {
        return switch (facing) {
            case EAST -> new BlockPos(-p.getZ(), p.getY(), p.getX());
            case SOUTH -> new BlockPos(-p.getX(), p.getY(), -p.getZ());
            case WEST -> new BlockPos(p.getZ(), p.getY(), -p.getX());
            default -> p;
        };
    }

    public static Vec3 rotate(Vec3 p, Direction facing) {
        return switch (facing) {
            case EAST -> new Vec3(-p.z, p.y, p.x);
            case SOUTH -> new Vec3(-p.x, p.y, -p.z);
            case WEST -> new Vec3(p.z, p.y, -p.x);
            default -> p;
        };
    }

    /** World position of an attachment point; the origin block's centre is the tower axis. */
    public static Vec3 world(BlockPos origin, Direction facing, Vec3 local) {
        Vec3 r = rotate(local, facing);
        return new Vec3(origin.getX() + 0.5 + r.x, origin.getY() + r.y, origin.getZ() + 0.5 + r.z);
    }
}
