package com.ptmuk.building;

import java.util.List;

/** Generated by tools/prefab_designs.py together with the structures. Do not edit by hand. */
public final class PrefabCatalog {
    public record Entry(String id, String name, String category, int width, int height, int depth, String description) {
    }

    public static final List<String> CATEGORIES = List.of("Houses", "Shops", "Offices", "Flats", "Other");

    public static final List<Entry> ENTRIES = List.of(
            new Entry("victorian_terrace", "Victorian Terraced House", "Houses", 7, 15, 19, "1 Victorian terraced house: bay window, slate roof, rear outrigger and yard."),
            new Entry("victorian_terrace_row", "Victorian Terrace (Row of 4)", "Houses", 25, 15, 19, "4 Victorian terraced houses: bay window, slate roof, rear outrigger and yard."),
            new Entry("victorian_terrace_red", "Victorian Terraced House (Red Brick)", "Houses", 7, 15, 19, "1 Victorian terraced house: bay window, slate roof, rear outrigger and yard."),
            new Entry("edwardian_semis", "Edwardian Semi-Detached Pair", "Houses", 21, 18, 21, "A pair of Edwardian semis: red brick, two-storey bays under mock-Tudor gables, tiled porches, clay tile roof."),
            new Entry("thirties_semis", "1930s Semi-Detached Pair", "Houses", 23, 18, 21, "A pair of 1930s semis: pebbledash over red brick, two-storey bays, leaded lights, clay tile roof and drives."),
            new Entry("council_terrace", "Post-war Council Houses (Terrace of 4)", "Houses", 25, 15, 20, "Four plain post-war council houses: red brick, wide windows, concrete door canopies, concrete tile roof, hedged gardens."),
            new Entry("newbuild_detached", "New-Build Detached House", "Houses", 16, 15, 21, "A 2020s new-build: red brick with a rendered front gable, grey windows, a canopy porch, garage and block-paved drive."),
            new Entry("bungalow", "1960s Bungalow", "Houses", 16, 10, 18, "A 1960s bungalow: brick under a hipped concrete tile roof, big picture window, side drive and a neat lawn."),
            new Entry("georgian_townhouse", "Georgian Townhouse", "Houses", 7, 24, 18, "A London Georgian townhouse: stucco ground floor, stock brick above, tall sash windows, iron balconettes, railings and a parapet."),
            new Entry("corner_shop", "Corner Shop with Flat Above", "Shops", 10, 14, 14, "A Victorian corner shop: shop front and fascia round the corner, flat above with its own door, slate roof."),
            new Entry("high_street_parade", "Victorian High Street Parade (3 Shops)", "Shops", 22, 17, 15, "Three Victorian shops with two floors of flats over: bakery, charity shop and barbers. Rename the signs in game."),
            new Entry("corner_pub", "Victorian Corner Pub", "Shops", 14, 18, 15, "A corner pub: green glazed tiles, gold-lettered fascia round the corner, hanging sign, bar and fireplace inside."),
            new Entry("cafe_takeaway", "Cafe and Takeaway (Pair)", "Shops", 15, 11, 13, "A 1950s two-shop parade with flats over: a cafe and a Chinese takeaway under a flat roof."),
            new Entry("bank", "Portland Stone Bank", "Shops", 13, 16, 15, "An Edwardian bank in Portland stone: tall windows between pilasters, a carved name band and a balustrade."),
            new Entry("convenience_store", "Modern Convenience Store", "Shops", 16, 7, 17, "A single-storey modern convenience store: glass frontage, big lit sign, flat roof and a small car park."),
            new Entry("glass_office", "Modern Glass Office Block", "Offices", 16, 29, 15, "Six storeys of curtain-wall glazing with dark spandrel bands, a canopied entrance and roof plant."),
            new Entry("sixties_office", "1960s Concrete Office Block", "Offices", 18, 33, 13, "Seven storeys of 1960s precast concrete: ribbon windows, vertical fins and a recessed glazed ground floor."),
            new Entry("brick_office", "1990s Brick Office", "Offices", 13, 19, 15, "A three-storey 1990s office: red brick, tinted glazing, a glass stair tower and a hipped roof over a car park."),
            new Entry("tower_block", "Council Tower Block (16 Storeys)", "Flats", 17, 53, 16, "A 1960s council tower block, refurbished: concrete and white panels, balconies, a named entrance and lift room."),
            new Entry("mansion_block", "1930s Mansion Block", "Flats", 21, 29, 14, "Five storeys of 1930s red-brick mansion flats: stone bands, a stone entrance bay with balconies, slate roof."),
            new Entry("modern_apartments", "Modern Apartment Block", "Flats", 19, 18, 15, "A 2010s apartment block: stock brick and grey cladding, big grey-framed windows, glass balconies and solar panels."),
            new Entry("deck_access_flats", "1960s Deck-Access Flats", "Flats", 25, 15, 12, "Low-rise 1960s council flats: brown brick, concrete walkway decks with front doors, stair towers at each end."),
            new Entry("church", "Victorian Parish Church", "Other", 15, 32, 27, "A small Victorian Gothic church: stone tower and spire, steep slate roof, lancet windows, pews and a churchyard."),
            new Entry("petrol_station", "Petrol Station", "Other", 22, 9, 21, "A forecourt with a lit canopy over four pump islands (EV chargers on one), a price board and a kiosk shop."));

    public static Entry get(String id) {
        for (Entry e : ENTRIES) {
            if (e.id().equals(id)) {
                return e;
            }
        }
        return null;
    }

    private PrefabCatalog() {
    }
}
