package com.ptmuk.bus;

import com.rinventor.ptm2.engine.vehicle.FloorObject;
import com.rinventor.ptm2.engine.vehicle.SeatLocation;
import com.rinventor.ptm2.engine.vehicle.WheelLocation;
import java.util.ArrayList;
import java.util.List;

/** Generated by tools/bus_alx400.py together with the model. Do not edit by hand. */
public final class ALX400Layout {
    public static final float LOWER_FLOOR = 0.380f;
    public static final float UPPER_FLOOR = 2.300f;
    /** Above this height (relative to the bus) the local player counts as being upstairs. */
    public static final double DECK_SWITCH_HEIGHT = 1.340;
    public static final double DOOR1_FORWARD = 4.350;
    public static final double DOOR2_FORWARD = 0.950;
    public static final double[] TICKET_MACHINE = {-0.12, 1.3, 4.35};
    /** Display sizes for the renderer: width, height (blocks) and label yaw. */
    public static final float[] DISPLAY_FRONT = {1.920f, 0.340f, 90.0f};
    public static final float[] DISPLAY_SIDE = {1.500f, 0.260f, 0.0f};
    public static final float[] DISPLAY_REAR = {0.700f, 0.280f, 270.0f};
    public static final float[] DISPLAY_INSIDE = {0.62f, 0.3f, 270.0f};
    public static final int SEAT_COUNT = 74;

    private ALX400Layout() {
    }

    public static List<SeatLocation> seats() {
        return new ArrayList<>(List.of(
                new SeatLocation(-0.720, 1.050, 4.350, 0.0f, false, -0.720, 0.380, 4.350),
                new SeatLocation(0.825, 1.630, 2.350, -90.0f, false, 0.000, 0.380, 2.350),
                new SeatLocation(0.825, 1.630, 2.850, -90.0f, false, 0.000, 0.380, 2.850),
                new SeatLocation(0.980, 1.380, -0.250, 0.0f, false, 0.000, 0.380, -0.250),
                new SeatLocation(0.530, 1.380, -0.250, 0.0f, false, 0.000, 0.380, -0.250),
                new SeatLocation(-0.530, 1.380, -0.250, 0.0f, false, 0.000, 0.380, -0.250),
                new SeatLocation(-0.980, 1.380, -0.250, 0.0f, false, 0.000, 0.380, -0.250),
                new SeatLocation(0.980, 1.380, -1.050, 0.0f, false, 0.000, 0.380, -1.050),
                new SeatLocation(0.530, 1.380, -1.050, 0.0f, false, 0.000, 0.380, -1.050),
                new SeatLocation(-0.530, 1.380, -1.050, 0.0f, false, 0.000, 0.380, -1.050),
                new SeatLocation(-0.980, 1.380, -1.050, 0.0f, false, 0.000, 0.380, -1.050),
                new SeatLocation(0.980, 1.380, -1.850, 0.0f, false, 0.000, 0.380, -1.850),
                new SeatLocation(0.530, 1.380, -1.850, 0.0f, false, 0.000, 0.380, -1.850),
                new SeatLocation(-0.530, 1.380, -1.850, 0.0f, false, 0.000, 0.380, -1.850),
                new SeatLocation(-0.980, 1.380, -1.850, 0.0f, false, 0.000, 0.380, -1.850),
                new SeatLocation(0.980, 1.630, -2.650, 0.0f, false, 0.000, 0.630, -2.650),
                new SeatLocation(0.530, 1.630, -2.650, 0.0f, false, 0.000, 0.630, -2.650),
                new SeatLocation(-0.530, 1.630, -2.650, 0.0f, false, 0.000, 0.630, -2.650),
                new SeatLocation(-0.980, 1.630, -2.650, 0.0f, false, 0.000, 0.630, -2.650),
                new SeatLocation(0.980, 1.630, -3.450, 0.0f, false, 0.000, 0.630, -3.450),
                new SeatLocation(0.530, 1.630, -3.450, 0.0f, false, 0.000, 0.630, -3.450),
                new SeatLocation(-0.530, 1.630, -3.450, 0.0f, false, 0.000, 0.630, -3.450),
                new SeatLocation(-0.980, 1.630, -3.450, 0.0f, false, 0.000, 0.630, -3.450),
                new SeatLocation(0.980, 1.380, -4.250, 0.0f, false, 0.000, 0.380, -4.250),
                new SeatLocation(0.530, 1.380, -4.250, 0.0f, false, 0.000, 0.380, -4.250),
                new SeatLocation(-0.530, 1.380, -4.250, 0.0f, false, 0.000, 0.380, -4.250),
                new SeatLocation(-0.980, 1.380, -4.250, 0.0f, false, 0.000, 0.380, -4.250),
                new SeatLocation(0.980, 3.300, 4.500, 0.0f, false, 0.000, 2.300, 4.500),
                new SeatLocation(0.530, 3.300, 4.500, 0.0f, false, 0.000, 2.300, 4.500),
                new SeatLocation(-0.530, 3.300, 4.500, 0.0f, false, 0.000, 2.300, 4.500),
                new SeatLocation(-0.980, 3.300, 4.500, 0.0f, false, 0.000, 2.300, 4.500),
                new SeatLocation(0.980, 3.300, 3.720, 0.0f, false, 0.000, 2.300, 3.720),
                new SeatLocation(0.530, 3.300, 3.720, 0.0f, false, 0.000, 2.300, 3.720),
                new SeatLocation(-0.530, 3.300, 3.720, 0.0f, false, 0.000, 2.300, 3.720),
                new SeatLocation(-0.980, 3.300, 3.720, 0.0f, false, 0.000, 2.300, 3.720),
                new SeatLocation(0.980, 3.300, 2.940, 0.0f, false, 0.000, 2.300, 2.940),
                new SeatLocation(0.530, 3.300, 2.940, 0.0f, false, 0.000, 2.300, 2.940),
                new SeatLocation(0.980, 3.300, 2.160, 0.0f, false, 0.000, 2.300, 2.160),
                new SeatLocation(0.530, 3.300, 2.160, 0.0f, false, 0.000, 2.300, 2.160),
                new SeatLocation(0.980, 3.300, 1.380, 0.0f, false, 0.000, 2.300, 1.380),
                new SeatLocation(0.530, 3.300, 1.380, 0.0f, false, 0.000, 2.300, 1.380),
                new SeatLocation(0.980, 3.300, 0.600, 0.0f, false, 0.000, 2.300, 0.600),
                new SeatLocation(0.530, 3.300, 0.600, 0.0f, false, 0.000, 2.300, 0.600),
                new SeatLocation(-0.530, 3.300, 0.600, 0.0f, false, 0.000, 2.300, 0.600),
                new SeatLocation(-0.980, 3.300, 0.600, 0.0f, false, 0.000, 2.300, 0.600),
                new SeatLocation(0.980, 3.300, -0.180, 0.0f, false, 0.000, 2.300, -0.180),
                new SeatLocation(0.530, 3.300, -0.180, 0.0f, false, 0.000, 2.300, -0.180),
                new SeatLocation(-0.530, 3.300, -0.180, 0.0f, false, 0.000, 2.300, -0.180),
                new SeatLocation(-0.980, 3.300, -0.180, 0.0f, false, 0.000, 2.300, -0.180),
                new SeatLocation(0.980, 3.300, -0.960, 0.0f, false, 0.000, 2.300, -0.960),
                new SeatLocation(0.530, 3.300, -0.960, 0.0f, false, 0.000, 2.300, -0.960),
                new SeatLocation(-0.530, 3.300, -0.960, 0.0f, false, 0.000, 2.300, -0.960),
                new SeatLocation(-0.980, 3.300, -0.960, 0.0f, false, 0.000, 2.300, -0.960),
                new SeatLocation(0.980, 3.300, -1.740, 0.0f, false, 0.000, 2.300, -1.740),
                new SeatLocation(0.530, 3.300, -1.740, 0.0f, false, 0.000, 2.300, -1.740),
                new SeatLocation(-0.530, 3.300, -1.740, 0.0f, false, 0.000, 2.300, -1.740),
                new SeatLocation(-0.980, 3.300, -1.740, 0.0f, false, 0.000, 2.300, -1.740),
                new SeatLocation(0.980, 3.300, -2.520, 0.0f, false, 0.000, 2.300, -2.520),
                new SeatLocation(0.530, 3.300, -2.520, 0.0f, false, 0.000, 2.300, -2.520),
                new SeatLocation(-0.530, 3.300, -2.520, 0.0f, false, 0.000, 2.300, -2.520),
                new SeatLocation(-0.980, 3.300, -2.520, 0.0f, false, 0.000, 2.300, -2.520),
                new SeatLocation(0.980, 3.300, -3.300, 0.0f, false, 0.000, 2.300, -3.300),
                new SeatLocation(0.530, 3.300, -3.300, 0.0f, false, 0.000, 2.300, -3.300),
                new SeatLocation(-0.530, 3.300, -3.300, 0.0f, false, 0.000, 2.300, -3.300),
                new SeatLocation(-0.980, 3.300, -3.300, 0.0f, false, 0.000, 2.300, -3.300),
                new SeatLocation(0.980, 3.300, -4.080, 0.0f, false, 0.000, 2.300, -4.080),
                new SeatLocation(0.530, 3.300, -4.080, 0.0f, false, 0.000, 2.300, -4.080),
                new SeatLocation(-0.530, 3.300, -4.080, 0.0f, false, 0.000, 2.300, -4.080),
                new SeatLocation(-0.980, 3.300, -4.080, 0.0f, false, 0.000, 2.300, -4.080),
                new SeatLocation(0.960, 3.300, -4.680, 0.0f, false, 0.000, 2.300, -4.680),
                new SeatLocation(0.480, 3.300, -4.680, 0.0f, false, 0.000, 2.300, -4.680),
                new SeatLocation(-0.000, 3.300, -4.680, 0.0f, false, 0.000, 2.300, -4.680),
                new SeatLocation(-0.480, 3.300, -4.680, 0.0f, false, 0.000, 2.300, -4.680),
                new SeatLocation(-0.960, 3.300, -4.680, 0.0f, false, 0.000, 2.300, -4.680)));
    }

    public static List<WheelLocation> wheels() {
        return new ArrayList<>(List.of(new WheelLocation(2.850), new WheelLocation(-2.850)));
    }

    /** The stairs first (so they win), then for the upper deck its floor everywhere else. */
    public static List<FloorObject> floors(boolean upper) {
        if (upper) {
            return new ArrayList<>(List.of(
                    new FloorObject(3.037, 3.300, 0.250, 1.220, 0.620f),
                    new FloorObject(2.775, 3.037, 0.250, 1.220, 0.860f),
                    new FloorObject(2.513, 2.775, 0.250, 1.220, 1.100f),
                    new FloorObject(2.250, 2.513, 0.250, 1.220, 1.340f),
                    new FloorObject(1.988, 2.250, 0.250, 1.220, 1.580f),
                    new FloorObject(1.725, 1.988, 0.250, 1.220, 1.820f),
                    new FloorObject(1.463, 1.725, 0.250, 1.220, 2.060f),
                    new FloorObject(1.200, 1.463, 0.250, 1.220, 2.300f),
                    new FloorObject(-5.100, 5.100, -2.550, 2.550, 2.300f)));
        }
        return new ArrayList<>(List.of(
                    new FloorObject(3.037, 3.300, 0.250, 1.220, 0.620f),
                    new FloorObject(2.775, 3.037, 0.250, 1.220, 0.860f),
                    new FloorObject(2.513, 2.775, 0.250, 1.220, 1.100f),
                    new FloorObject(2.250, 2.513, 0.250, 1.220, 1.340f),
                    new FloorObject(1.988, 2.250, 0.250, 1.220, 1.580f),
                    new FloorObject(1.725, 1.988, 0.250, 1.220, 1.820f),
                    new FloorObject(1.463, 1.725, 0.250, 1.220, 2.060f),
                    new FloorObject(1.200, 1.463, 0.250, 1.220, 2.300f)));
    }
}
