package com.ptmuk.bus;

import com.rinventor.ptm2.engine.vehicle.FloorObject;
import com.rinventor.ptm2.engine.vehicle.SeatLocation;
import com.rinventor.ptm2.engine.vehicle.WheelLocation;
import java.util.ArrayList;
import java.util.List;

/** Generated by tools/bus_alx400.py together with the model. Do not edit by hand. */
public final class ALX400Layout implements BusLayout {
    public static final ALX400Layout INSTANCE = new ALX400Layout();

    public static final float LOWER_FLOOR = 0.425f;
    public static final float UPPER_FLOOR = 2.891f;
    /** Above this height (relative to the bus) the local player counts as being upstairs. */
    public static final double DECK_SWITCH_HEIGHT = 1.658;
    public static final double DOOR1_FORWARD = 4.773;
    public static final double DOOR2_FORWARD = -1.569;
    public static final double[] TICKET_MACHINE = {-0.047, 1.381, 4.708};
    /** Display sizes for the renderer: width, height (blocks) and label yaw. */
    // label yaws measured in game: 90 faces the front, 180 the nearside, 270 the rear
    public static final float[] DISPLAY_FRONT = {1.605f, 0.684f, 90.0f};
    public static final float[] DISPLAY_SIDE = {1.652f, 0.260f, 180.0f};
    public static final float[] DISPLAY_REAR = {0.732f, 0.354f, 270.0f};
    public static final float[] DISPLAY_INSIDE = {0.732f, 0.354f, 270.0f};
    public static final int SEAT_COUNT = 76;

    private ALX400Layout() {
    }

    @Override public float lowerFloor() { return LOWER_FLOOR; }
    @Override public double deckSwitchHeight() { return DECK_SWITCH_HEIGHT; }
    @Override public double door1Forward() { return DOOR1_FORWARD; }
    @Override public double door2Forward() { return DOOR2_FORWARD; }
    @Override public double[] ticketMachine() { return TICKET_MACHINE; }
    @Override public float[] displayFront() { return DISPLAY_FRONT; }
    @Override public float[] displaySide() { return DISPLAY_SIDE; }
    @Override public float[] displayRear() { return DISPLAY_REAR; }
    @Override public float[] displayInside() { return DISPLAY_INSIDE; }
    @Override public List<SeatLocation> seatList() { return seats(); }
    @Override public List<WheelLocation> wheelList() { return wheels(); }
    @Override public List<FloorObject> floorList(boolean upper) { return floors(upper); }
    /** The fleet number sits on the black band under the windscreen. */
    @Override public int frontIdColour() { return 0xFFF0F0F0; }

    public static List<SeatLocation> seats() {
        return new ArrayList<>(List.of(
                new SeatLocation(-0.850, 1.097, 5.133, 0.0f, false, -0.850, 0.425, 5.133),
                new SeatLocation(0.702, 1.333, 2.891, -90.0f, false, 0.000, 0.425, 2.891),
                new SeatLocation(0.702, 1.333, 3.481, -90.0f, false, 0.000, 0.425, 3.481),
                new SeatLocation(1.156, 1.038, 1.888, 0.0f, false, 0.000, 0.425, 1.888),
                new SeatLocation(0.625, 1.038, 1.888, 0.0f, false, 0.000, 0.425, 1.888),
                new SeatLocation(1.156, 1.038, 0.944, 0.0f, false, 0.000, 0.425, 0.944),
                new SeatLocation(0.625, 1.038, 0.944, 0.0f, false, 0.000, 0.425, 0.944),
                new SeatLocation(1.156, 1.038, 0.000, 0.0f, false, 0.000, 0.425, 0.000),
                new SeatLocation(0.625, 1.038, 0.000, 0.0f, false, 0.000, 0.425, 0.000),
                new SeatLocation(-0.625, 1.038, 0.944, 0.0f, false, 0.000, 0.425, 0.944),
                new SeatLocation(-1.156, 1.038, 0.944, 0.0f, false, 0.000, 0.425, 0.944),
                new SeatLocation(-0.625, 1.038, 0.000, 0.0f, false, 0.000, 0.425, 0.000),
                new SeatLocation(-1.156, 1.038, 0.000, 0.0f, false, 0.000, 0.425, 0.000),
                new SeatLocation(1.156, 1.534, -2.891, 0.0f, false, 0.000, 0.920, -2.891),
                new SeatLocation(0.625, 1.534, -2.891, 0.0f, false, 0.000, 0.920, -2.891),
                new SeatLocation(-0.625, 1.534, -2.891, 0.0f, false, 0.000, 0.920, -2.891),
                new SeatLocation(-1.156, 1.534, -2.891, 0.0f, false, 0.000, 0.920, -2.891),
                new SeatLocation(1.156, 1.534, -3.835, 0.0f, false, 0.000, 0.920, -3.835),
                new SeatLocation(0.625, 1.534, -3.835, 0.0f, false, 0.000, 0.920, -3.835),
                new SeatLocation(-0.625, 1.534, -3.835, 0.0f, false, 0.000, 0.920, -3.835),
                new SeatLocation(-1.156, 1.534, -3.835, 0.0f, false, 0.000, 0.920, -3.835),
                new SeatLocation(1.156, 1.038, -4.779, 0.0f, false, 0.000, 0.425, -4.779),
                new SeatLocation(0.625, 1.038, -4.779, 0.0f, false, 0.000, 0.425, -4.779),
                new SeatLocation(-0.625, 1.038, -4.779, 0.0f, false, 0.000, 0.425, -4.779),
                new SeatLocation(-1.156, 1.038, -4.779, 0.0f, false, 0.000, 0.425, -4.779),
                new SeatLocation(1.156, 1.392, -5.487, 0.0f, false, 0.000, 0.779, -5.487),
                new SeatLocation(0.625, 1.392, -5.487, 0.0f, false, 0.000, 0.779, -5.487),
                new SeatLocation(-0.625, 1.392, -5.487, 0.0f, false, 0.000, 0.779, -5.487),
                new SeatLocation(-1.156, 1.392, -5.487, 0.0f, false, 0.000, 0.779, -5.487),
                new SeatLocation(1.156, 3.505, 5.310, 0.0f, false, 0.000, 2.891, 5.310),
                new SeatLocation(0.625, 3.505, 5.310, 0.0f, false, 0.000, 2.891, 5.310),
                new SeatLocation(-0.625, 3.505, 5.310, 0.0f, false, 0.000, 2.891, 5.310),
                new SeatLocation(-1.156, 3.505, 5.310, 0.0f, false, 0.000, 2.891, 5.310),
                new SeatLocation(1.156, 3.505, 4.390, 0.0f, false, 0.000, 2.891, 4.390),
                new SeatLocation(0.625, 3.505, 4.390, 0.0f, false, 0.000, 2.891, 4.390),
                new SeatLocation(-0.625, 3.505, 4.390, 0.0f, false, 0.000, 2.891, 4.390),
                new SeatLocation(-1.156, 3.505, 4.390, 0.0f, false, 0.000, 2.891, 4.390),
                new SeatLocation(1.156, 3.505, 3.469, 0.0f, false, 0.000, 2.891, 3.469),
                new SeatLocation(0.625, 3.505, 3.469, 0.0f, false, 0.000, 2.891, 3.469),
                new SeatLocation(1.156, 3.505, 2.549, 0.0f, false, 0.000, 2.891, 2.549),
                new SeatLocation(0.625, 3.505, 2.549, 0.0f, false, 0.000, 2.891, 2.549),
                new SeatLocation(1.156, 3.505, 1.628, 0.0f, false, 0.000, 2.891, 1.628),
                new SeatLocation(0.625, 3.505, 1.628, 0.0f, false, 0.000, 2.891, 1.628),
                new SeatLocation(1.156, 3.505, 0.708, 0.0f, false, 0.000, 2.891, 0.708),
                new SeatLocation(0.625, 3.505, 0.708, 0.0f, false, 0.000, 2.891, 0.708),
                new SeatLocation(-0.625, 3.505, 0.708, 0.0f, false, 0.000, 2.891, 0.708),
                new SeatLocation(-1.156, 3.505, 0.708, 0.0f, false, 0.000, 2.891, 0.708),
                new SeatLocation(1.156, 3.505, -0.212, 0.0f, false, 0.000, 2.891, -0.212),
                new SeatLocation(0.625, 3.505, -0.212, 0.0f, false, 0.000, 2.891, -0.212),
                new SeatLocation(-0.625, 3.505, -0.212, 0.0f, false, 0.000, 2.891, -0.212),
                new SeatLocation(-1.156, 3.505, -0.212, 0.0f, false, 0.000, 2.891, -0.212),
                new SeatLocation(1.156, 3.505, -1.133, 0.0f, false, 0.000, 2.891, -1.133),
                new SeatLocation(0.625, 3.505, -1.133, 0.0f, false, 0.000, 2.891, -1.133),
                new SeatLocation(-0.625, 3.505, -1.133, 0.0f, false, 0.000, 2.891, -1.133),
                new SeatLocation(-1.156, 3.505, -1.133, 0.0f, false, 0.000, 2.891, -1.133),
                new SeatLocation(1.156, 3.505, -2.053, 0.0f, false, 0.000, 2.891, -2.053),
                new SeatLocation(0.625, 3.505, -2.053, 0.0f, false, 0.000, 2.891, -2.053),
                new SeatLocation(-0.625, 3.505, -2.053, 0.0f, false, 0.000, 2.891, -2.053),
                new SeatLocation(-1.156, 3.505, -2.053, 0.0f, false, 0.000, 2.891, -2.053),
                new SeatLocation(1.156, 3.505, -2.974, 0.0f, false, 0.000, 2.891, -2.974),
                new SeatLocation(0.625, 3.505, -2.974, 0.0f, false, 0.000, 2.891, -2.974),
                new SeatLocation(-0.625, 3.505, -2.974, 0.0f, false, 0.000, 2.891, -2.974),
                new SeatLocation(-1.156, 3.505, -2.974, 0.0f, false, 0.000, 2.891, -2.974),
                new SeatLocation(1.156, 3.505, -3.894, 0.0f, false, 0.000, 2.891, -3.894),
                new SeatLocation(0.625, 3.505, -3.894, 0.0f, false, 0.000, 2.891, -3.894),
                new SeatLocation(-0.625, 3.505, -3.894, 0.0f, false, 0.000, 2.891, -3.894),
                new SeatLocation(-1.156, 3.505, -3.894, 0.0f, false, 0.000, 2.891, -3.894),
                new SeatLocation(1.156, 3.505, -4.814, 0.0f, false, 0.000, 2.891, -4.814),
                new SeatLocation(0.625, 3.505, -4.814, 0.0f, false, 0.000, 2.891, -4.814),
                new SeatLocation(-0.625, 3.505, -4.814, 0.0f, false, 0.000, 2.891, -4.814),
                new SeatLocation(-1.156, 3.505, -4.814, 0.0f, false, 0.000, 2.891, -4.814),
                new SeatLocation(0.991, 3.505, -5.475, 0.0f, false, 0.000, 2.891, -5.475),
                new SeatLocation(0.496, 3.505, -5.475, 0.0f, false, 0.000, 2.891, -5.475),
                new SeatLocation(-0.000, 3.505, -5.475, 0.0f, false, 0.000, 2.891, -5.475),
                new SeatLocation(-0.496, 3.505, -5.475, 0.0f, false, 0.000, 2.891, -5.475),
                new SeatLocation(-0.991, 3.505, -5.475, 0.0f, false, 0.000, 2.891, -5.475)));
    }

    public static List<WheelLocation> wheels() {
        return new ArrayList<>(List.of(new WheelLocation(3.245), new WheelLocation(-3.363)));
    }

    /** The stairs first (so they win), then for the upper deck its floor everywhere else. */
    public static List<FloorObject> floors(boolean upper) {
        if (upper) {
            return new ArrayList<>(List.of(
                    new FloorObject(3.584, 3.894, 0.295, 1.440, 0.733f),
                    new FloorObject(3.274, 3.584, 0.295, 1.440, 1.041f),
                    new FloorObject(2.965, 3.274, 0.295, 1.440, 1.350f),
                    new FloorObject(2.655, 2.965, 0.295, 1.440, 1.658f),
                    new FloorObject(2.345, 2.655, 0.295, 1.440, 1.966f),
                    new FloorObject(2.035, 2.345, 0.295, 1.440, 2.274f),
                    new FloorObject(1.726, 2.035, 0.295, 1.440, 2.583f),
                    new FloorObject(1.416, 1.726, 0.295, 1.440, 2.891f),
                    new FloorObject(-6.018, 6.018, -3.009, 3.009, 2.891f)));
        }
        return new ArrayList<>(List.of(
                    new FloorObject(3.584, 3.894, 0.295, 1.440, 0.733f),
                    new FloorObject(3.274, 3.584, 0.295, 1.440, 1.041f),
                    new FloorObject(2.965, 3.274, 0.295, 1.440, 1.350f),
                    new FloorObject(2.655, 2.965, 0.295, 1.440, 1.658f),
                    new FloorObject(2.345, 2.655, 0.295, 1.440, 1.966f),
                    new FloorObject(2.035, 2.345, 0.295, 1.440, 2.274f),
                    new FloorObject(1.726, 2.035, 0.295, 1.440, 2.583f),
                    new FloorObject(1.416, 1.726, 0.295, 1.440, 2.891f)));
    }
}
